/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uiInterfaces;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;

import static entities.User.getPasswordByUsername;
import static entities.User.updateParolaBD;

/**
 *
 * @author Sclav
 */
public class ChangePasswordFrame extends javax.swing.JFrame {

    /**
     * Creates new form ChangePasswordFrame
     */
    public ChangePasswordFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jTextFieldUsername = new javax.swing.JTextField();
        jTextFieldParolaVeche = new javax.swing.JTextField();
        jTextFieldParolaNoua = new javax.swing.JTextField();
        labelSchimbaParola = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        labelParolaVeche = new javax.swing.JLabel();
        labelParolaNoua = new javax.swing.JLabel();
        btnChangePassword = new javax.swing.JButton();
        labelRepetaParolaNoua = new javax.swing.JLabel();
        labelConfrimare = new javax.swing.JLabel();
        jTextFieldRepetaParolaNoua = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Change password");

        jTextFieldUsername.setText("jTextField1");

        jTextFieldParolaVeche.setText("jTextField2");

        jTextFieldParolaNoua.setText("jTextField3");

        labelSchimbaParola.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelSchimbaParola.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSchimbaParola.setText("Schimba parola");

        labelUsername.setText("Username");

        labelParolaVeche.setText("Parola veche");

        labelParolaNoua.setText("Parola noua");

        btnChangePassword.setText("Salveaza modificari");

        labelRepetaParolaNoua.setText("Repeta parola");

        labelConfrimare.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelConfrimare.setText("jLabel6");

        jTextFieldRepetaParolaNoua.setText("jTextField1");

        btnChangePassword.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent arg0) {
                //trebuie sa luam textul din fiecare textField
                String username = jTextFieldUsername.getText();
                String parolaVeche = jTextFieldParolaVeche.getText();
                String parolaNoua = jTextFieldParolaNoua.getText();
                String parolaNouaRepeta = jTextFieldRepetaParolaNoua.getText();

                //trebuie sa vedem daca username-ul si parola sunt ca in baza de date
                String parolaBD = null;
                try {
                    parolaBD = getPasswordByUsername(username);
                } catch (SQLException e) {
                    e.printStackTrace();
                } catch (ClassNotFoundException e) {
                    e.printStackTrace();
                }
                if(parolaVeche.equals(parolaBD)) {
                    //trebuie sa vedem daca parola noua = repetare parola noua
                    if(parolaNoua.equals(parolaNouaRepeta)){
                        //trebuie sa facem update pe baza de date si sa dam mesaj: parola sch succes!
                        try {
                            updateParolaBD(username,parolaNoua);
                            labelConfrimare.setText("SUCCESS: Parola schimbata!");
                        } catch (SQLException e) {
                            e.printStackTrace();
                            labelConfrimare.setText("ERROR: Update esuat!");
                        } catch (ClassNotFoundException e) {
                            e.printStackTrace();
                            labelConfrimare.setText("ERROR: Update esuat!");
                        }
                    } else {
                        labelConfrimare.setText("ERROR: Parola noua repetata incorect!");
                    }
                } else {
                    labelConfrimare.setText("ERROR: Username sau parola veche incorecte!");
                }
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelSchimbaParola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(labelParolaNoua)
                                                        .addComponent(labelRepetaParolaNoua)
                                                        .addComponent(labelUsername)
                                                        .addComponent(labelParolaVeche))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jTextFieldParolaVeche, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextFieldParolaNoua, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextFieldRepetaParolaNoua, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(btnChangePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(102, 102, 102))
                        .addComponent(labelConfrimare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(labelSchimbaParola, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelUsername))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldParolaVeche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelParolaVeche))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldParolaNoua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelParolaNoua))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelRepetaParolaNoua)
                                        .addComponent(jTextFieldRepetaParolaNoua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelConfrimare)
                                .addContainerGap(51, Short.MAX_VALUE))
        );

        labelRepetaParolaNoua.getAccessibleContext().setAccessibleName("Repeta parola");
        labelRepetaParolaNoua.getAccessibleContext().setAccessibleDescription("");
        labelConfrimare.getAccessibleContext().setAccessibleName("labelConfrimare");

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePasswordFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JTextField jTextFieldParolaNoua;
    private javax.swing.JTextField jTextFieldParolaVeche;
    private javax.swing.JTextField jTextFieldRepetaParolaNoua;
    private javax.swing.JTextField jTextFieldUsername;
    private javax.swing.JLabel labelConfrimare;
    private javax.swing.JLabel labelParolaNoua;
    private javax.swing.JLabel labelParolaVeche;
    private javax.swing.JLabel labelRepetaParolaNoua;
    private javax.swing.JLabel labelSchimbaParola;
    private javax.swing.JLabel labelUsername;
    // End of variables declaration
}
