//---cod Ana begin---//
package uiInterfaces;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;

import javax.swing.JPasswordField;

/**
 *
 * @author Sclav
 */
public class ChangePasswordFrame extends javax.swing.JFrame {

    private Connection conn;
    private Statement stmt;
    private String statut;
    private String username;

    public void updateParolaBD(String username, char[] parolaNoua) throws SQLException, ClassNotFoundException {
        System.out.println("Updating parola");
        stmt = conn.createStatement();
        String sql = "UPDATE LoginData\n" +
                "SET password = SHA1('" + new String(parolaNoua) +
                "') WHERE username = '" + username + "';";
        stmt.executeUpdate(sql);
        System.out.println("Updated parola");
    }

    /**
     * Creates new form ChangePasswordFrame
     */
    public ChangePasswordFrame(Connection conn, String username, String statut) {
        this.conn = conn;
        this.statut = statut;
        this.username = username;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        labelSchimbaParola = new javax.swing.JLabel();
        labelParolaNoua = new javax.swing.JLabel();
        btnChangePassword = new javax.swing.JButton();
        labelRepetaParolaNoua = new javax.swing.JLabel();
        labelConfrimare = new javax.swing.JLabel();
        jPasswordFieldParolaNoua = new javax.swing.JPasswordField();
        jPasswordFieldRepetaParolaNoua = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Change password");

        labelSchimbaParola.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelSchimbaParola.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSchimbaParola.setText("Schimba parola");

        labelParolaNoua.setText("Parola noua");

        btnChangePassword.setText("Salveaza modificari");

        labelRepetaParolaNoua.setText("Repeta parola");

        labelConfrimare.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelConfrimare.setText("---------");

        jPasswordFieldParolaNoua.setText("");

        jPasswordFieldRepetaParolaNoua.setText("");

        btnChangePassword.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent arg0) {
                //trebuie sa luam textul din fiecare textField
                //char[] parolaVeche = jPasswordFieldParolaVeche.getPassword();
                char[] parolaNoua = jPasswordFieldParolaNoua.getPassword();
                char[] parolaNouaRepeta = jPasswordFieldRepetaParolaNoua.getPassword();

                /*//trebuie sa vedem daca username-ul si parola sunt ca in baza de date
                LoginDatabase loginDatabase = LoginDatabase.getAccess(username, parolaVeche);
                System.out.println(username + parolaVeche);
                if(loginDatabase.getConnection() == null)
                    JOptionPane.showMessageDialog(null, "Userul sau parola este gresita!");
                else {conn = loginDatabase.getConnection();}*/

                //trebuie sa vedem daca parola noua = repetare parola noua
                if (Arrays.equals(parolaNoua, parolaNouaRepeta)) {
                    //trebuie sa facem update pe baza de date si sa dam mesaj: parola sch succes!
                    try {
                        updateParolaBD(username, parolaNoua);
                        labelConfrimare.setText("SUCCESS: Parola schimbata!");
                    } catch (SQLException | ClassNotFoundException e) {
                        e.printStackTrace();
                        labelConfrimare.setText("ERROR: Update error!");
                    }
                } else{
                    labelConfrimare.setText("ERROR: Parola noua repetata incorect!");
                }
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelSchimbaParola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelConfrimare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnChangePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addComponent(labelRepetaParolaNoua))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(labelParolaNoua)
                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jPasswordFieldParolaNoua, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jPasswordFieldRepetaParolaNoua, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(102, 102, 102))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(labelSchimbaParola, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelParolaNoua)
                                        .addComponent(jPasswordFieldParolaNoua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelRepetaParolaNoua)
                                        .addComponent(jPasswordFieldRepetaParolaNoua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelConfrimare)
                                .addContainerGap(35, Short.MAX_VALUE))
        );

        labelRepetaParolaNoua.getAccessibleContext().setAccessibleDescription("");
        labelConfrimare.getAccessibleContext().setAccessibleName("labelConfrimare");

        pack();
    }// </editor-fold>

    // Variables declaration - do not modify
    private javax.swing.JButton btnChangePassword;
    private JPasswordField jPasswordFieldParolaNoua;
    private javax.swing.JPasswordField jPasswordFieldRepetaParolaNoua;
    private javax.swing.JLabel labelConfrimare;
    private javax.swing.JLabel labelParolaNoua;
    private javax.swing.JLabel labelRepetaParolaNoua;
    private javax.swing.JLabel labelSchimbaParola;
}
//---cod Ana end---//